# [START app_yaml]
runtime: nodejs
env: basic
automatic_scaling:
min_num_instances: 1
max_num_instances: 1
max_concurrent_requests: 80
cpu_utilization:
target_utilization: 0.8
resources:
cpu: 0.05
memory_gb: 0.5
disk_size_gb: 10
